language: node_js
sudo: false
node_js:
- '7'
install:
- npm install -g typescript
script:
- tsc
deploy:
 provider: pages
 skip_cleanup: true
 keep-history: true
 github_token: $GITHUB_TOKEN
 on:
   branch: master
